config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :adverts
  devise_for :users
  resources :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :adverts
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if can? :manage, @user

    else
      redirect_to home_index_url
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if can? :manage, @user

    else
      redirect_to home_index_url
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if can? :manage, @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    else
      redirect_to home_index_url
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :address, :telephone)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :class => "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, :class => "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone, :class => "form-control"  %>
  </div>
<br>
  <div class="actions">
    <%= form.submit "Salvar", :class => "btn btn-success btn-lg botao"%>
  </div>
  <br>
<% end %>

app/views/users/edit.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home/index">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Novo anúncio', new_advert_path %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path) %>
          </li>

        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
      </form>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar conta", edit_user_registration_path %></li>
              <%user = current_user %>
              <li><%= link_to 'Meus anúncios', adverts_path(:id=>user.id)%></li>
              <%if current_user.admin? == true %>
                <li><%= link_to "Usuários", users_path %></li>
                <li><%= link_to "Criar categoria", new_category_path %></li>
                <li><%= link_to "Categorias", categories_path %></li>
              <%end %>
              <li role="separator" class="divider"></li>
              <li><a <%= link_to('Sair', destroy_user_session_path, method: :delete) %></a></li>

            </ul>
      <% end %>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid col-xs-6 col-md-4 col-md-offset-4">

  <br>
  <br>
      <div class="panel-heading">
        <h3 class="panel-title"><strong><h3 class="text-center">Editar informações de cadastro</h3></strong></h3>
      </div>

    <%= render 'form', user: @user %>

    <%= link_to 'Visualizar', @user, :class => "btn btn-info botao" %>
    <%= link_to 'Voltar', users_path, :class => "btn btn-primary botao"%>
</div>

app/views/users/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home/index">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Novo anúncio', new_advert_path %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path) %>
          </li>

        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
      </form>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar conta", edit_user_registration_path %></li>
              <%user = current_user %>
              <li><%= link_to 'Meus anúncios', adverts_path(:id=>user.id)%></li>
              <%if current_user.admin? == true %>
                <li><%= link_to "Usuários", users_path %></li>
                <li><%= link_to "Criar categoria", new_category_path %></li>
                <li><%= link_to "Categorias", categories_path %></li>
              <%end %>
              <li role="separator" class="divider"></li>
              <li><a <%= link_to('Sair', destroy_user_session_path, method: :delete) %></a></li>

            </ul>
      <% end %>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <br>
  <br>
  <p id="notice"><%= notice %></p>

  <h1>Usuários</h1>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Nome</th>
      <th>Endereço</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.address %></td>
        <td><%= user.telephone %></td>
        <td><%= link_to 'Visualizar Conta', user, :class => "btn btn-info botao" %></td>
        <%if can? :manage, user %>
          <td><%= link_to 'Edit', edit_user_path(user), :class => "btn btn-warning botao" %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger botao" %></td>
        <%end %>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/users/new.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home/index">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Novo anúncio', new_advert_path %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path) %>
          </li>

        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
      </form>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar conta", edit_user_registration_path %></li>
              <%user = current_user %>
              <li><%= link_to 'Meus anúncios', adverts_path(:id=>user.id)%></li>
              <%if current_user.admin? == true %>
                <li><%= link_to "Usuários", users_path %></li>
                <li><%= link_to "Criar categoria", new_category_path %></li>
                <li><%= link_to "Categorias", categories_path %></li>
              <%end %>
              <li role="separator" class="divider"></li>
              <li><a <%= link_to('Sair', destroy_user_session_path, method: :delete) %></a></li>

            </ul>
      <% end %>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <br>
  <br>
<h1>Novo usuário</h1>

<%= render 'form', user: @user %>

  <%= link_to 'Voltar', users_path, :class => "btn btn-primary botao"%>
</div>

app/views/users/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home/index">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Novo anúncio', new_advert_path %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path) %>
          </li>

        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
      </form>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar conta", edit_user_registration_path %></li>
              <%user = current_user %>
              <li><%= link_to 'Meus anúncios', adverts_path(:id=>user.id)%></li>
              <%if current_user.admin? == true %>
                <li><%= link_to "Usuários", users_path %></li>
                <li><%= link_to "Criar categoria", new_category_path %></li>
                <li><%= link_to "Categorias", categories_path %></li>
              <%end %>
              <li role="separator" class="divider"></li>
              <li><a <%= link_to('Sair', destroy_user_session_path, method: :delete) %></a></li>

            </ul>
      <% end %>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>


<div class="container-fluid">
  <br>
  <br>
  <br>
  <p id="notice"><%= notice %></p>


  <p>
    <strong>Nome:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Endereço:</strong>
    <%= @user.address %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= @user.telephone %>
  </p>
  <%user = @user %>
  <%if can? :manage, user %>

  <%= link_to 'Editar', edit_user_path(@user), :class => "btn btn-warning botao" %>
  <%end %>
  <%= link_to 'Voltar', users_path, :class => "btn btn-primary botao" %>
</div>