config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :adverts
  devise_for :users
  resources :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/advert.rb
class Advert < ApplicationRecord
  belongs_to :user
  belongs_to :category
  mount_uploaders :images, PhotosUploader
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :price
  validates_presence_of :images

  scope :titleSearch, -> (title) { where("UPPER (adverts.title) like ?", "%#{title.upcase}%")}

  def increment(by = 1)
    self.views ||= 0
    self.views += by
    self.save
  end
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :set_advert, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :homepage
  skip_authorize_resource :only => :homepage
  # GET /adverts
  # GET /adverts.json
  def index

    if params[:titleSearch].nil?
      if params[:category_id].nil?
        if params[:id].nil?
          @adverts = Advert.all
          @adverts = Advert.order(:views).order(:title)
          @categories = Category.all
        else
          @adverts = Advert.where(:user_id => params[:id]).order(:views).order(:title)
          @categories = Category.all
        end

      else
        if params[:id].nil?
          @adverts = Advert.where(:category_id => params[:category_id]).order(:views).order(:title)
          @categories = Category.all
          flash[:notice] = "Existem <b>#{@adverts.count}</b> anúncios nessa categoria".html_safe
        else
          @adverts = Advert.where(:category_id => params[:category_id]).order(:views).order(:title)
          @adverts = Advert.where(:user_id => params[:id]).order(:views).order(:title)
          @categories = Category.all
        end

      end

    else
      if params[:category_id].nil?
        if params[:id].nil?
          @adverts = Advert.titleSearch(params[:titleSearch]).order(:views).order(:title)
          @categories = Category.all
        else
          @adverts = Advert.titleSearch(params[:titleSearch]).order(:views).order(:title)
          @adverts = Advert.where(:user_id => params[:id]).order(:views).order(:title)
          @categories = Category.all
        end

      else
        if params[:id].nil?
          @adverts = Advert.where(:category_id => params[:category_id]).order(:views).order(:title)
          @adverts = Advert.titleSearch(params[:titleSearch]).order(:views).order(:title)
          @categories = Category.all
          flash[:notice] = "Existem <b>#{@adverts.count}</b> anúncios nessa categoria".html_safe
        else
          @adverts = Advert.where(:category_id => params[:category_id]).order(:views).order(:title)
          @adverts = Advert.titleSearch(params[:titleSearch]).order(:views).order(:title)
          @adverts = Advert.where(:user_id => params[:id]).order(:views).order(:title)
          @categories = Category.all
          flash[:notice] = "Existem <b>#{@adverts.count}</b> anúncios nessa categoria".html_safe
        end

      end

    end


    end

  # GET /adverts/1
  # GET /adverts/1.json
  def show
    @adverts = Advert.all
    @adverts = Advert.where(:category_id => @advert.category_id).order(:views).order(:title)
    @advert.increment
  end

  # GET /adverts/new
  def new
    @advert = Advert.new
    @advert.images = params[:images]
  end

  # GET /adverts/1/edit
  def edit
    if can? :manage, @advert

    else
      redirect_to home_index_url
    end
  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = Advert.new(advert_params)
    @advert.user = current_user
    @advert.views = 0
    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: 'Advert was successfully created.' }
        format.json { render :show, status: :created, location: @advert }
      else
        format.html { render :new }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adverts/1
  # PATCH/PUT /adverts/1.json
  def update
    respond_to do |format|
      if @advert.update(advert_params)
        format.html { redirect_to @advert, notice: 'Advert was successfully updated.' }
        format.json { render :show, status: :ok, location: @advert }
      else
        format.html { render :edit }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert.destroy
    respond_to do |format|
      format.html { redirect_to adverts_url, notice: 'Advert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advert
      @advert = Advert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advert_params
      params.require(:advert).permit(:title, :description, :price, :category_id, :user_id, {images: []}, :titleSearch)
    end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
  def post_date(date)
    # formatting date: Aug, 31 2007 - 9:55PM
    date.strftime("%b, %d %H:%M")
  end

  def resume(text)
    # text[0..300] + "..."
    truncate(text, length: 30)
  end
end

app/views/adverts/_form.html.erb
<%= form_with(model: advert, local: true) do |form| %>
  <% if advert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advert.errors.count, "error") %> prohibited this advert from being saved:</h2>

      <ul>
      <% advert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :'Título' %>
    <%= form.text_field :title, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :'Descrição' %>
    <%= form.text_field :description, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :'Preço' %>
    <%= form.number_field :price, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :'Categoria' %>
    <%= form.select :category_id, Category.all.collect {|category| [category.name, category.id]}, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :'Imagens' %>
    <%= form.file_field :images, multiple: true%>
  </div>

  <div class="actions">
    <%= form.submit "Salvar", :class => "btn btn-success btn-lg botao"%>
  </div>
  <br>
<% end %>

app/views/adverts/edit.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home/index">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Novo anúncio', new_advert_path %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path) %>
          </li>

        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
      </form>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar conta", edit_user_registration_path %></li>
              <%user = current_user %>
              <li><%= link_to 'Meus anúncios', adverts_path(:id=>user.id)%></li>
              <%if current_user.admin? == true %>
                <li><%= link_to "Usuários", users_path %></li>
                <li><%= link_to "Criar categoria", new_category_path %></li>
                <li><%= link_to "Categorias", categories_path %></li>
              <%end %>
              <li role="separator" class="divider"></li>
              <li><a <%= link_to('Sair', destroy_user_session_path, method: :delete) %></a></li>

            </ul>
      <% end %>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid col-xs-6 col-md-4 col-md-offset-4">

  <br>
  <br>
  <%advert = @advert %>
  <%if can? :manage, advert %>
    <div class="panel-heading">
      <h3 class="panel-title"><strong><h3 class="text-center">Editar informações do anúncio</h3></strong></h3>
    </div>

    <%= render 'form', advert: @advert %>

    <%= link_to 'Visualizar', @advert, :class => "btn btn-info" %> |
    <%= link_to 'Voltar', adverts_path, :class => "btn btn-primary"%>
  <%end %>

</div>

app/views/adverts/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home/index">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Novo anúncio', new_advert_path %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path) %>
          </li>

        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <%= form_tag('/adverts', method: 'get') do %>
            <input type="text" class="form-control " placeholder="Buscar por título" <%= text_field_tag(:titleSearch) %>
            </div>
            <button type="submit" class="btn btn-default">Buscar</button>
          <% end %>
          </form>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar conta", edit_user_registration_path %></li>
              <%user = current_user %>
              <li><%= link_to 'Meus anúncios', adverts_path(:id=>user.id)%></li>
              <%if current_user.admin? == true %>
              <li><%= link_to "Usuários", users_path %></li>
                <li><%= link_to "Criar categoria", new_category_path %></li>
                <li><%= link_to "Categorias", categories_path %></li>
                <%end %>
              <li role="separator" class="divider"></li>
              <li><a <%= link_to('Sair', destroy_user_session_path, method: :delete) %></a></li>

            </ul>
      <% end %>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <br>
  <br>


  <h1>Anúncios</h1>

  <div class="panel panel-default painel">
    <div class="panel-heading">Categorias</div>
    <div class="panel-body">
      <p id="notice"><%= notice %></p>
      <table class="table">
        <thead>
        <tr>
          <th>Nome</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= link_to category.name, adverts_path(:category_id=>category.id)%></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-md-offset-3 ">
    <% @adverts.each do |advert| %>
      <div class="col-sm-8">
        <div class="thumbnail thumb">
          <div class="">

            <div class="painel">
              <% p = advert.images[0]%>
              <%= link_to (image_tag(p.thumb.url) unless p.file.nil?), advert %>

            </div>
            <div>
              <%= %>
            </div>
            <div class="caption">
              <div class="">
                <div  class="col-sm-6 " style="max-width: 200px;">
                  <h3><%=resume advert.title %></h3>
                </div>
                <div class="info-advert">
                  <h4><%= post_date advert.created_at %></h4>
                </div>
                <div class="info-ajuste">
                  <h4><strong>R$ <%= advert.price %></strong></h4>
                </div>


              </div>
            </div>
          </div>
        </div>
      </div>


    <%end %>
  </div>



</div>

app/views/adverts/new.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home/index">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Novo anúncio', new_advert_path %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path) %>
          </li>

        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
      </form>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar conta", edit_user_registration_path %></li>
              <%user = current_user %>
              <li><%= link_to 'Meus anúncios', adverts_path(:id=>user.id)%></li>
              <%if current_user.admin? == true %>
                <li><%= link_to "Usuários", users_path %></li>
                <li><%= link_to "Criar categoria", new_category_path %></li>
                <li><%= link_to "Categorias", categories_path %></li>
              <%end %>
              <li role="separator" class="divider"></li>
              <li><a <%= link_to('Sair', destroy_user_session_path, method: :delete) %></a></li>

            </ul>
      <% end %>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>


<div class="container-fluid col-xs-6 col-md-4 col-md-offset-4">

  <br>
  <br>
    <div class="panel-heading">
      <h3 class="panel-title"><strong><h3 class="text-center">Inserir novo anúncio</h3></strong></h3>
    </div>

    <%= render 'form', advert: @advert %>
    <%= link_to 'Voltar', adverts_path, :class => "btn btn-primary botao"%>


</div>

app/views/adverts/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home/index">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Novo anúncio', new_advert_path %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path) %>
          </li>

        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
          </form>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar conta", edit_user_registration_path %></li>
              <%user = current_user %>
              <li><%= link_to 'Meus anúncios', adverts_path(:id=>user.id)%></li>
              <%if current_user.admin? == true %>
                <li><%= link_to "Usuários", users_path %></li>
                <li><%= link_to "Criar categoria", new_category_path %></li>
                <li><%= link_to "Categorias", categories_path %></li>
              <%end %>
              <li role="separator" class="divider"></li>
              <li><a <%= link_to('Sair', destroy_user_session_path, method: :delete) %></a></li>

            </ul>
      <% end %>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <br>
  <br>
  <br>
  <p id="notice"><%= notice %></p>

  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title"><strong><%= @advert.title %></strong></h3>
    </div>
    <div class="panel-body">
      <strong>Descrição:</strong>
      <%= @advert.description %>
      <br>
      <strong>Preço:</strong>
      <%= @advert.price %>
      <br>
      <p>
        <strong>Data de inserção do anúncio:</strong>
        <%= post_date @advert.created_at %>
        <br>
        <strong>Nome Vendedor: </strong><%= @advert.user.name %>
        <br>
        <strong>Telefone do vendedor:</strong>
        <%= @advert.user.telephone %>
        <br>
        <strong>Endereço do vendedor:</strong>
        <%= @advert.user.address%>
        <br>
        <strong>Email do vendedor:</strong>
        <%= @advert.user.email%>
        <br>
        <strong>Visualizações do anúncio:</strong>
        <%= @advert.views%>
      </p>

      <div style="
      clear: both;
          display: table;">
        <% @advert.images.each do |photo|%>
          <div style="  float: left;

              padding: 5px;">
            <%= link_to (image_tag(photo.thumb.url) unless photo.file.nil?), photo.url%>
          </div>
        <% end %>
      </div>
      <br>
      <%advert = @advert %>
      <%if can? :manage, advert %>
        <%= link_to 'Editar', edit_advert_path(@advert), :class => "btn btn-warning botao"  %>
        <%= link_to 'Apagar', @advert, method: :delete, data: { confirm: 'Tem certeza que deseja apagar?' }, :class => "btn btn-danger botao"  %>
      <%end %>

    </div>
  </div>

  <%= link_to 'Voltar', adverts_path, :class => "btn-lg btn-primary botao"  %>


  <h2>Anúncios com a mesma categoria</h2>
  <br>
  <div class="col-md-offset-3 ">
    <% @adverts.each do |advert| %>
      <div class="col-sm-8">
        <div class="thumbnail thumb">
          <div class="">

            <div class="painel">
              <% p = advert.images[0]%>
              <%= link_to (image_tag(p.thumb.url) unless p.file.nil?), advert%>

            </div>
            <div>
              <%= %>
            </div>
            <div class="caption">
              <div class="">
                <div  class="col-sm-6 lg-max-painel">
                  <h3><%=resume advert.title %></h3>
                </div>
                <div style="float: right;     height: inherit;
                    padding: 10px 0 0 0;
                    width: 56px;">
                  <h4><%= post_date advert.created_at %></h4>
                </div>
                <div style="float: right;     height: inherit;
                    padding: 16px 0 0 0;
                    width: 96px;;">
                  <h4><strong>R$ <%= advert.price %></strong></h4>
                </div>


              </div>
            </div>
          </div>
        </div>
      </div>


    <%end %>
  </div>


</div>