config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :adverts
  devise_for :users
  resources :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :adverts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    if can? :manage, @category

    else
      redirect_to home_index_url

    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    if can? :manage, @category

    else
      redirect_to home_index_url
    end

  end

  # POST /categories
  # POST /categories.json
  def create
    if can? :manage, @category

    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
    else
      redirect_to home_index_url
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    if can? :manage, @category
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
    else
      redirect_to home_index_url
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :'Nome da categoria' %>
    <%= form.text_field :name, :class => "form-control"  %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Salvar", :class => "btn btn-success btn-lg botao"%>
  </div>
  <br>
<% end %>

app/views/categories/edit.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home/index">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Novo anúncio', new_advert_path %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path) %>
          </li>

        <% end %>
      </ul>

      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar conta", edit_user_registration_path %></li>
              <%if current_user.admin? == true %>
                <li><%= link_to "Usuários", users_path %></li>
                <li><%= link_to "Criar categoria", new_category_path %></li>
                <li><%= link_to "Categorias", categories_path %></li>
              <%end %>
              <li role="separator" class="divider"></li>
              <li><a <%= link_to('Sair', destroy_user_session_path, method: :delete) %></a></li>

            </ul>
      <% end %>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <br>
  <br>
  <br>
  <div class="container-fluid col-xs-6 col-md-4 col-md-offset-4">

    <br>
    <br>

    <div class="panel-heading">
      <h3 class="panel-title"><strong><h3 class="text-center">Editar informações da categoria</h3></strong></h3>
    </div>

    <%= render 'form', category: @category %>

    <%= link_to 'Visualizar', @category, :class => "btn btn-info botao" %>
    <%= link_to 'Voltar', categories_path, :class => "btn btn-primary botao"%>

  </div>
</div>

app/views/categories/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home/index">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Novo anúncio', new_advert_path %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path) %>
          </li>

        <% end %>
      </ul>

      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar conta", edit_user_registration_path %></li>
              <%if current_user.admin? == true %>
                <li><%= link_to "Usuários", users_path %></li>
                <li><%= link_to "Criar categoria", new_category_path %></li>
                <li><%= link_to "Categorias", categories_path %></li>
              <%end %>
              <li role="separator" class="divider"></li>
              <li><a <%= link_to('Sair', destroy_user_session_path, method: :delete) %></a></li>

            </ul>
      <% end %>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <br>
  <br>
  <br>
<p id="notice"><%= notice %></p>

<h1>Categorias cadastradas</h1>

<table class=" table table-stripped">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <%if can? :manage, category %>
        <td><%= link_to 'Editar', edit_category_path(category), :class => "btn btn-warning botao" %></td>
        <td><%= link_to 'Apagar', category, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger botao" %></td>
          <%end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/categories/new.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home/index">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Novo anúncio', new_advert_path %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path) %>
          </li>

        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
      </form>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar conta", edit_user_registration_path %></li>
              <%user = current_user %>
              <li><%= link_to 'Meus anúncios', adverts_path(:id=>user.id)%></li>
              <%if current_user.admin? == true %>
                <li><%= link_to "Usuários", users_path %></li>
                <li><%= link_to "Criar categoria", new_category_path %></li>
                <li><%= link_to "Categorias", categories_path %></li>
              <%end %>
              <li role="separator" class="divider"></li>
              <li><a <%= link_to('Sair', destroy_user_session_path, method: :delete) %></a></li>

            </ul>
      <% end %>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid col-xs-6 col-md-4 col-md-offset-4">

  <br>
  <br>
  <div class="panel-heading">
    <h3 class="panel-title"><strong><h3 class="text-center">Inserir nova categoria</h3></strong></h3>
  </div>

  <%= render 'form', category: @category %>
  <%= link_to 'Voltar', categories_path, :class => "btn btn-primary botao"%>


</div>

app/views/categories/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home/index">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Novo anúncio', new_advert_path %></li>
        <% else %>
          <li>
            <%= link_to('Login', new_user_session_path) %>
          </li>

        <% end %>
      </ul>

      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar conta", edit_user_registration_path %></li>
              <%if current_user.admin? == true %>
                <li><%= link_to "Usuários", users_path %></li>
                <li><%= link_to "Criar categoria", new_category_path %></li>
                <li><%= link_to "Categorias", categories_path %></li>
              <%end %>
              <li role="separator" class="divider"></li>
              <li><a <%= link_to('Sair', destroy_user_session_path, method: :delete) %></a></li>

            </ul>
      <% end %>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <br>
  <br>
  <br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @category.name %>
</p>

  <%= link_to 'Editar', edit_category_path(@category), :class => "btn btn-warning botao"  %>
  <%= link_to 'Voltar', categories_path, :class => "btn btn-primary botao"%>
</div>